### PR TITLE
Add sbversion parameter to docker builds

### PR DESCRIPTION
**Pull request by andrewsavage1**
b/264712142

### CODE REVIEW

**Review by isarkis — CHANGES_REQUESTED** [review]
GCB is failing, see https://pantheon.corp.google.com/cloud-build/builds;region=us-west1/6a19ac19-b372-4edb-931e-75b3ff0aa313;step=15?project=cobalt-buildbot-gcr

**Comment by andrewsavage1** [comment]
Currently gcb attempts to build linux-x64x11-sbversion12-evergreen. Does anyone know if we actually need this?

**Comment by isarkis** [comment]
> Currently gcb attempts to build linux-x64x11-sbversion12-evergreen. Does anyone know if we actually need this?

We need linux-x64x11-evergreen worker for Buildbot.

**Comment by andrewsavage1** [comment]
> We need linux-x64x11-evergreen worker for Buildbot.

That's fine, but that builder doesn't have anything to do with sbversion 12. I'll update the names temporarily

**Review by isarkis — APPROVED** [review]

**Comment by kaidokert** [comment]
Possibly ready to go in ? GCB has been okay

**Pull request merged**
