### PR TITLE
Add Starboard thread_sampler APIs to Android

### PR DESCRIPTION
**Pull request by aelzeiny**
Swaps Starboard's thread_sampler APIs for Android TV from stub to shared implementations (`//starboard/shared/stub/thread_sampler_*` to `//starboard/shared/pthread/thread_sampler_*`).

Tested on Android TV (x64), Google TV Emulator (arm64), and a real Google TV device (arm).

Test-On-Device: true

b/330564529

### CODE REVIEW

**Review by zhongqiliang — APPROVED** [review]
LGTM.
The orignal implementation is https://lbshell-internal-review.git.corp.google.com/c/starboard/+/123104

**Comment by zhongqiliang** [comment]
Please wait for x86  on device tests to be verified.

**Review by kaidokert — APPROVED** [review]
looks ready to land

**Comment by aelzeiny** [comment]
Merging

**Pull request merged**
