### PR TITLE
Angle update

### PR DESCRIPTION
**Pull request by niranjanyardi**
b/323209852

Test-On-Device: true

### CODE REVIEW

**Comment by niranjanyardi** [comment]
xb1 tests pass: https://screenshot.googleplex.com/4XKAAanhousvgwA

**Comment by v-kryachko** [comment]
Configuration `linux-x64x11-clang-3-9` has failed to build. Is this configuration really required?

**Review by amurovanyi — APPROVED** [review]

**Comment by kaidokert** [comment]
To fix clang-3.9 and gcc-6.3, this PR needs to land first: #3595

**Comment by v-kryachko** [comment]
It looks like evergreen-x64 tests failed, because the version of Cobalt binary in update is incompatible with Starboard 16.

**Pull request closed without merging**
