### PR TITLE
Disable HttpServerTest

### PR DESCRIPTION
**Pull request by sherryzy**
b/327658019

### CODE REVIEW

**Comment by andrewsavage1** [comment]
We can simply switch the default initializer in that test to be a normal initialization of a struct (i.e. `{.foo = foo}` just becomes `{foo}`)

**Comment by sherryzy** [comment]
@andrewsavage1 I saw you added some other disabled tests and gated by # Re-enable once we're on c++20. I thought they are for this type of error, no?

**Comment by andrewsavage1** [comment]
> @andrewsavage1 I saw you added some other disabled tests and gated by # Re-enable once we're on c++20. I thought they are for this type of error, no?

We can do the same for this test, but those tests fail with other things that required more in-depth fixes and the default initialization fixes were relatively easy (and also necessary in some non-test locations, so I figured I'd do the same for tests). If you just want to disable it until we compile with c++20 that's fine as it's a P3

**Review by andrewsavage1 — APPROVED** [review]
Feel free to submit or change to fixing the test at your discretion

**Comment by sherryzy** [comment]
@andrewsavage1 It's just one line of change, I totally agree we can make a change and enable the test. I'll try to do that. (Though as I don't have a windows machine, I need to rely on the Actions here to tell me if the anything breaks. And it's not very efficient. So if it takes more effort to make it pass, I probably will go ahead and just disable the test.)

**Comment by andrewsavage1** [comment]
Would you please change the title before submitting (assuming you're going to continue to include the test)?

**Pull request merged**
