### PR TITLE
Make the qa build debuggable

### PR DESCRIPTION
**Pull request by jellefoks**
Make the qa build debuggable, just as the devel and debug already are, so that you can pull output/test files off the device without needing debug-keys or rooted devices.

b/0nobugforlinter

### CODE REVIEW

**Review by zhongqiliang — APPROVED** [review]
LGTM

**Review by kaidokert — APPROVED** [review]
lgtm but is there a performance downside, or anything ?

**Comment by jellefoks** [comment]
> lgtm but is there a performance downside, or anything ?

I didn't notice one in my other investigations, but the qa package may get larger this way. I didn't check that.

**Comment by kaidokert** [comment]
> > lgtm but is there a performance downside, or anything ?
> 
> I didn't notice one in my other investigations, but the qa package may get larger this way. I didn't check that.

One thing is that Play store distribution may block this on production channels. To be fair, QA config shouldn't go to production channels anyway, but our alpha/fishfood may be impacted.

Also if it incurs any performance overhead this would be not great - as QA is our stand-in for all production testing.

**Comment by jellefoks** [comment]
> > > lgtm but is there a performance downside, or anything ?
> > 
> > 
> > I didn't notice one in my other investigations, but the qa package may get larger this way. I didn't check that.
> 
> One thing is that Play store distribution may block this on production channels. To be fair, QA config shouldn't go to production channels anyway, but our alpha/fishfood may be impacted.
> 
> Also if it incurs any performance overhead this would be not great - as QA is our stand-in for all production testing.

I did not see a performance degradation. If play store deployment is an issue, then a solution would be to build QA builds for the app store differently from CoAT builds where debugging of QA builds is really useful.

**Pull request merged**
