### PR TITLE
[media] changing FFMpeg MACROs to function calls. (#174)

### PR DESCRIPTION
**Pull request by sideb0ard**
b/184697040

### CODE REVIEW

**Review by kaidokert — APPROVED** [review]
lgtm if builds pass - they didn't yet

**Review by kaidokert — CHANGES_REQUESTED** [review]
Please hold the cherry-pick until we work out if this is the cause of build breaks here: b/184697040#comment29

**Comment by sideb0ard** [comment]
> Please hold the cherry-pick until we work out if this is the cause of build breaks here: b/184697040#comment29

this looks good i think - you agree?

**Comment by kaidokert** [comment]
Yes looking good, lets go ahead and cherrypick

**Review by kaidokert — APPROVED** [review]

**Pull request merged**
