### PR TITLE
Remove unused core dump handler code

### PR DESCRIPTION
**Pull request by hlwarriner**
b/289214111

Change-Id: If822f5879010dd4235c49c01f01a43b287652d68

### CODE REVIEW

**Comment by hlwarriner** [comment]
@jellefoks @niranjanyardi, can you please take a look at https://b.corp.google.com/issues/289214111#comment2 and help me evaluate whether any of this core dump data is actually needed? If so, I think we'd want to add it back by 1) possibly extending the CrashHandler Starboard extension to take key/value pairs with Int or Float values, and 2) using the Starboard extension where we previously used `SbCoreDumpLog{String, Integer, Float}`.

**Review by jellefoks — APPROVED** [review]
I agree that is appears to be dead code now.

**Comment by niranjanyardi** [comment]
> @jellefoks @niranjanyardi, can you please take a look at [b.corp.google.com/issues/289214111#comment2](https://b.corp.google.com/issues/289214111#comment2) and help me evaluate whether any of this core dump data is actually needed? If so, I think we'd want to add it back by 1) possibly extending the CrashHandler Starboard extension to take key/value pairs with Int or Float values, and 2) using the Starboard extension where we previously used `SbCoreDumpLog{String, Integer, Float}`.

thanks for the comment. lgtm ,  did you run tests on ps5 and ensure that passes ?

**Review by niranjanyardi — APPROVED** [review]

**Review by joeltine — APPROVED** [review]
Change LGTM. It is a tad scary removing this stuff because if we inadvertently break crash context logging, a lot of downstream stuff breaks horribly.

Can you just verify you've tested everything adequately and are confident PlayStation 5 still works and other platforms still work as expected? Thanks!

**Comment by hlwarriner** [comment]
> > @jellefoks @niranjanyardi, can you please take a look at [b.corp.google.com/issues/289214111#comment2](https://b.corp.google.com/issues/289214111#comment2) and help me evaluate whether any of this core dump data is actually needed? If so, I think we'd want to add it back by 1) possibly extending the CrashHandler Starboard extension to take key/value pairs with Int or Float values, and 2) using the Starboard extension where we previously used `SbCoreDumpLog{String, Integer, Float}`.
> 
> thanks for the comment. lgtm , did you run tests on ps5 and ensure that passes ?

You're welcome and not yet - I think I'll need to use the corresponding Gerrit change to run try builds.

**Comment by hlwarriner** [comment]
> Change LGTM. It is a tad scary removing this stuff because if we inadvertently break crash context logging, a lot of downstream stuff breaks horribly.
> 
> Can you just verify you've tested everything adequately and are confident PlayStation 5 still works and other platforms still work as expected? Thanks!

You're mostly worried about preserving the client context set by the web app via the `setString` web API, right? I was planning to test locally on a couple Evergreen platforms, like x64 and AOSP, just to be sure there's no regression. But ps5 is the platform that would be more likely to have a regression, I guess. @niranjanyardi, do we have a way to force a crash locally on ps5 and inspect the crash report?

**Comment by joeltine** [comment]
> > Change LGTM. It is a tad scary removing this stuff because if we inadvertently break crash context logging, a lot of downstream stuff breaks horribly.
> > Can you just verify you've tested everything adequately and are confident PlayStation 5 still works and other platforms still work as expected? Thanks!
> 
> You're mostly worried about preserving the client context set by the web app via the `setString` web API, right? I was planning to test locally on a couple Evergreen platforms, like x64 and AOSP, just to be sure there's no regression. But ps5 is the platform that would be more likely to have a regression, I guess. @niranjanyardi, do we have a way to force a crash locally on ps5 and inspect the crash report?

Ya. Ideally, we could test all of Apple, PS5, EG, and Android. I  _believe_ the YTS tests that Wei wrote recently should cover some of this, right?

**Comment by hlwarriner** [comment]
> > > Change LGTM. It is a tad scary removing this stuff because if we inadvertently break crash context logging, a lot of downstream stuff breaks horribly.
> > > Can you just verify you've tested everything adequately and are confident PlayStation 5 still works and other platforms still work as expected? Thanks!
> > 
> > 
> > You're mostly worried about preserving the client context set by the web app via the `setString` web API, right? I was planning to test locally on a couple Evergreen platforms, like x64 and AOSP, just to be sure there's no regression. But ps5 is the platform that would be more likely to have a regression, I guess. @niranjanyardi, do we have a way to force a crash locally on ps5 and inspect the crash report?
> 
> Ya. Ideally, we could test all of Apple, PS5, EG, and Android. I _believe_ the YTS tests that Wei wrote recently should cover some of this, right?

Wei's cl/586080954 modified the existing `verify the crash handler functionality` test so that it now exercises the `setString` web API. The test is still somewhat incomplete in this respect though because we haven't added the verification of the data in the crash report (https://b.corp.google.com/issues/310979503#comment9). This behavior is easy enough to test end-to-end manually on Evergreen devices, so I'll probably just do that for x64 and AOSP, anyway. Also, note this YTS test is Evergreen specific, so can't help with other platforms.

For ps5, @niranjanyardi offered to help test this locally. Based on the discussion in b/249761235, I think we should be able to verify that the ps5 crash has the expected client context after we force a crash.

For Apple and Android, I can talk to platform owners and see how much effort it would be to validate that `setString` still works correctly. It would be very surprising if it didn't, since these changes are mostly scoped to platforms that define `CORE_DUMP_HANDLER_SUPPORT`, which I think used to be just Playstation and now is no platform, but we can at least look into testing it.

Longer term we should think about whether we can write end-to-end tests for `setString` for non-Evergreen platforms.

**Comment by hlwarriner** [comment]
> on

@niranjanyardi spent some time looking into this but it sounds like we currently don't have a way to verify that this change doesn't cause a regression w.r.t. the `setString` implementation on ps5. From what I understand, the problem is that 1) there's no way to generate/upload a "reported crash" from a devkit or testkit, and 2) feature request b/181902049 is still open.

@joeltine, are you ok with merging this?

**Comment by hlwarriner** [comment]
> > there's no way to generate/upload a "reported crash" from a devkit or testkit,
> 
> This seems problematic in general. Did we verify this with Sony?

@niranjanyardi or @madhurajayaraman can you please comment?

I agree we should have a way to manually test this end-to-end - maybe we can increase the priority of b/181902049? But if we don't have a way to end-to-end test this currently - and it sounds like we don't - I'd like to not block this cleanup.

**Comment by joeltine** [comment]
> > > there's no way to generate/upload a "reported crash" from a devkit or testkit,
> > 
> > 
> > This seems problematic in general. Did we verify this with Sony?
> 
> @niranjanyardi or @madhurajayaraman can you please comment?
> 
> I agree we should have a way to manually test this end-to-end - maybe we can increase the priority of b/181902049? But if we don't have a way to end-to-end test this currently - and it sounds like we don't - I'd like to not block this cleanup.

Yes, please proceed if there's no expedient way to test this. I'd just be a bit surprised if Sony didn't have a way to trigger crash reports in a dev environment.

**Comment by niranjanyardi** [comment]
> > > > there's no way to generate/upload a "reported crash" from a devkit or testkit,
> > > 
> > > 
> > > This seems problematic in general. Did we verify this with Sony?
> > 
> > 
> > @niranjanyardi or @madhurajayaraman can you please comment?
> > I agree we should have a way to manually test this end-to-end - maybe we can increase the priority of b/181902049? But if we don't have a way to end-to-end test this currently - and it sounds like we don't - I'd like to not block this cleanup.
> 
> Yes, please proceed if there's no expedient way to test this. I'd just be a bit surprised if Sony didn't have a way to trigger crash reports in a dev environment.

I asked sony, subscribed you to the support request.

**Comment by hlwarriner** [comment]
> > > > > there's no way to generate/upload a "reported crash" from a devkit or testkit,
> > > > 
> > > > 
> > > > This seems problematic in general. Did we verify this with Sony?
> > > 
> > > 
> > > @niranjanyardi or @madhurajayaraman can you please comment?
> > > I agree we should have a way to manually test this end-to-end - maybe we can increase the priority of b/181902049? But if we don't have a way to end-to-end test this currently - and it sounds like we don't - I'd like to not block this cleanup.
> > 
> > 
> > Yes, please proceed if there's no expedient way to test this. I'd just be a bit surprised if Sony didn't have a way to trigger crash reports in a dev environment.
> 
> I asked sony, subscribed you to the support request.

Thanks, Niranjan. And sorry, I just have one more question on this: even if the crash report isn't "reported," is one still generated on the device that can be inspected locally somehow? Maybe we can ask Sony this, too, if we're not sure.

**Comment by niranjanyardi** [comment]
> > > > > > there's no way to generate/upload a "reported crash" from a devkit or testkit,
> > > > > 
> > > > > 
> > > > > This seems problematic in general. Did we verify this with Sony?
> > > > 
> > > > 
> > > > @niranjanyardi or @madhurajayaraman can you please comment?
> > > > I agree we should have a way to manually test this end-to-end - maybe we can increase the priority of b/181902049? But if we don't have a way to end-to-end test this currently - and it sounds like we don't - I'd like to not block this cleanup.
> > > 
> > > 
> > > Yes, please proceed if there's no expedient way to test this. I'd just be a bit surprised if Sony didn't have a way to trigger crash reports in a dev environment.
> > 
> > 
> > I asked sony, subscribed you to the support request.
> 
> Thanks, Niranjan. And sorry, I just have one more question on this: even if the crash report isn't "reported," is one still generated on the device that can be inspected locally somehow? Maybe we can ask Sony this, too, if we're not sure.

>> Good point Joel. I generated a coredump on my ps5 devkit and it does have the user info , see: https://screenshot.googleplex.com/9FckKQ4bS7jdsdH  .   So we have successfully verified this change doesnt break ps5

**Pull request merged**
