### PR TITLE
Update default build containers to Debian 11

### PR DESCRIPTION
**Pull request by kaidokert**
This addresses a few container deployment issues, and makes binaries built on Debian 11 based hosts default compatible with the containers.

b/291067151
b/291066320

### CODE REVIEW

**Comment by kaidokert** [comment]
Depends on go/cobalt-cl/260221

**Comment by isarkis** [comment]
> go/cobalt-cl/260221

This PR needs to land before go/cobalt-cl/260221, is that correct?

**Comment by kaidokert** [comment]
> > go/cobalt-cl/260221
> 
> This PR needs to land before go/cobalt-cl/260221, is that correct?

The internal one actually needs to go in first - and that is still failing.

**Comment by kaidokert** [comment]
Moving this to https://github.com/youtube/cobalt/pull/2009 where it's mostly reviewed

**Pull request closed without merging**
