### PR TITLE
Merge V8 version 8.8.278.17

### PR DESCRIPTION
**Pull request by dahlstrom-g**
This is a small update to the latest 8.8 version:
https://chromium.googlesource.com/v8/v8/+log/8.8-lkgr
There were no merge conflicts.

### CODE REVIEW

**Review by kaidokert — APPROVED** [review]
Mostly looks like a clean update to me. A few test jobs failed - just for peace of mind, would be good to retry only the failing ones.

Lets work look at how to get that to 24lts as well once merged - or we can leave it trunk only as well.

Would be good for another reviewer to take a quick look.

**Comment by johnxwork** [comment]
The code changes look good, I'm excited about the next steps!

We recently switched to github workflow so please wait for review from andrewsavage@ to ensure we are doing rebase in the right way(to keep commit history e.t.c)

The lint pre-submit check is complaining about missing bug ID. The other test failures might be flakes(usually we don't see so many flakes, maybe it's due to recently enabled tests). You can re-run the failed test steps to check.

**Comment by kaidokert** [comment]
> The lint pre-submit check is complaining about missing bug ID.

This one is currently expected, because subtree squashes produce merge commits that won't have bug ID in them. In the longer run, we'll redesign the Bug ID check to run this per-PR, not per individual commit.

**Comment by dahlstrom-g** [comment]
> The code changes look good, I'm excited about the next steps!

Thanks! I'm sure it will get harder. ; )

> We recently switched to github workflow so please wait for review from andrewsavage@ to ensure we are doing rebase in the right way(to keep commit history e.t.c)

That part I think I understand; it should be good to go.
The `git-subtree.sh` contrib script uses these [trailers](git-scm.com/docs/git-interpret-trailers):
```
git-subtree-dir: third_party/v8
git-subtree-split: f7f4327516912dfca0d7401044e890ca0ce885ad
```

> The lint pre-submit check is complaining about missing bug ID.

Yeah—it seems weird to add a buganizer link to the upstream commit metadata
but I suppose I could. As long as the check can be ignored, though, it's OK with me.

> The other test failures might be flakes(usually we don't see so many flakes, maybe it's due to recently enabled tests). You can re-run the failed test steps to check.

I did that; the android-arm check passed but the evergreen ones are still in progress.

Finally (maybe it's obvious) the commits in this PR shouldn't be squashed together.

**Comment by kaidokert** [comment]
> it seems weird to add a Buganizer link to the upstream commit metadata but I suppose I could.

No let's not do that - the problem is with Bug ID check as is't currently set up. We'll bypass the check when merging. We'll just have to let people know internally as well that this is OK for now.

**Comment by dahlstrom-g** [comment]
> I did that; the android-arm check passed but the evergreen ones are still in progress.

The evergreen checks succeeded on the third try (82 min +94 min +54 min ≈ 230 min not including retry lag).

**Comment by dahlstrom-g** [comment]
The evergreen checks succeeded on the third try (after running 82 min + 94 min +54 min ≈ 230 min, not including retry lag).

**Comment by kaidokert** [comment]
You are getting failed checks on Raspi-2 here because base commit was already broken ( metrics_test was deleted in trunk). It's now fixed in trunk - we can go ahead and merge this as is, if it's otherwise ready.

**Comment by dahlstrom-g** [comment]
> You are getting failed checks on Raspi-2 here because base commit was already broken ( metrics_test was deleted in trunk). It's now fixed in trunk - we can go ahead and merge this as is, if it's otherwise ready. Let me know - merging with merge button requires admin powers for now.

LGTM

**Pull request merged**
