### PR TITLE
Stop free scrolling on app hide

### PR DESCRIPTION
**Pull request by andrewsavage1**
b/290655439
b/290846002

### CODE REVIEW

**Comment by andrewsavage1** [comment]
@jellefoks let me know if you think I'm using the wrong lifecycle states here

**Review by kaidokert — APPROVED** [review]
Resetting scroll on Conceal/Freeze makes sense to me

**Comment by andrewsavage1** [comment]
@kaidokert @sherryzy would y'all be able to take another look after the more recent commits? Thanks!

**Comment by kaidokert** [comment]
> @kaidokert @sherryzy would y'all be able to take another look after the more recent commits? Thanks!

Looks fine to me, the cleanup in destructor looks correct

**Comment by andrewsavage1** [comment]
Here's the current failure that I'm debugging, happens during the `CancelSyncLoadsWhenSuspended` black box test:

```
[cobalt/6330:0720/181732.787827:INFO:application.cc(1196)] Got blur event.
[DebugConsoleWebModule/6364:0720/181732.787986:INFO:application_lifecycle_state.cc(153)] SetApplicationState: kApplicationStateStarted (1) -> kApplicationStateBlurred (2)
[cobalt/6330:0720/181732.788248:FATAL:observer_list_internal.h(73)] Check failed: false. 
        base::internal::CheckedObserverAdapter::IsMarkedForRemoval() [0x56156fe7ba00]
        base::ObserverList<>::Iter::EnsureValidIndex() [0x56156fe7b194]
        base::ObserverList<>::Iter::operator++() [0x56156fe5736a]
        cobalt::browser::BrowserModule::Blur() [0x56156fe36e67]
        cobalt::browser::Application::OnApplicationEvent() [0x56156fe108f5]
        cobalt::browser::Application::HandleStarboardEvent() [0x56156fe1145c]
        SbEventHandle [0x56156cc07d78]
        starboard::shared::starboard::Application::HandleEventAndUpdateState() [0x561571e6c461]
        starboard::shared::starboard::Application::DispatchAndDelete() [0x561571e6ab3b]
        starboard::shared::starboard::Application::RunLoop() [0x561571e67a2e]
        starboard::shared::starboard::Application::Run() [0x561571e681d3]
        main [0x561571c6102e]
        __libc_start_main [0x7f53ab8ca09b]
        _start [0x56156cb3dfea]
```

Haven't been able to recreate it by manually sending SIGUSR1 to the cobalt process after launching it. Tried replacing the call to `RemoveObserver` with a `PostTask` that ensures it is done in the browser modular thread as splash screen destruction does, but that didn't seem to help. I'm also noticing that Cobalt seem to crash in general during black box tests if it is hidden in some way, i.e. if I click to another window.

**Review by jellefoks — APPROVED** [review]

**Comment by andrewsavage1** [comment]
Even after [`3623b78` (#901)](https://github.com/youtube/cobalt/pull/901/commits/3623b785863d1a39102ee3ea28fcf919684df68b) I'm still occasionally running into the failing `IsDesignated` `DCHECK` in `TopmostEventTarget`.

**Comment by andrewsavage1** [comment]
> Even after [`3623b78` (#901)](https://github.com/youtube/cobalt/pull/901/commits/3623b785863d1a39102ee3ea28fcf919684df68b) I'm still occasionally running into the failing `IsDesignated` `DCHECK` in `TopmostEventTarget`. This happened when messing around on the secondary side nav for the settings page.

Oh, well of course it didn't, I didn't use the `previous_html_element_weak_` pointer in the call to `DispatchPointerEventsForScrollStart`. Fixed in [`ed06432` (#901)](https://github.com/youtube/cobalt/pull/901/commits/ed0643231671439c0835466d03e1d6d18deff423)

**Review by jellefoks — APPROVED** [review]

**Review by sherryzy — APPROVED** [review]

**Comment by andrewsavage1** [comment]
Merging to unblock Sherry in writing black box tests, but we'll keep an eye on if we see regressions in scroll behavior

**Pull request merged**
