### PR TITLE
Turn ANRs for offloaded SourceBuffer to crash

### PR DESCRIPTION
**Pull request by xiaomings**
This CL affects all platforms.

ANRs were observed when SourceBuffer offload is enabled on Android TV. It's likely that one of the relevant threads is deadlocked during suspend, but we are unable to get a callstack of the offending thread.

This CL turns the ANRs into crashes, by adding CHECKs around the only mutex introduced by SourceBuffer offload, to crash when the mutex is re-acquired on the same thread, or when it takes too long to acquire. This doesn't resolve the original bug, but will allow us to get the callstack of the offending thread for further debugging.

b/223283615
b/271167555

### CODE REVIEW

**Review by kaidokert — APPROVED** [review]
Small lint check fail, otherwise lgtm

**Comment by xiaomings** [comment]
Lint failure resolved by reformatting.

**Review by jasonzhangxx — APPROVED** [review]
LGTM.

**Comment by tphamg** [comment]
I think "acquired_thread_id_" needs to be part of the mutex or passed in by reference / pointer. ScopedLockWhenRequired is always used as a function-local object, so the checks in the constructor and destructor will always pass. For example, even if you had:

void Foo() {
  ScopedLockWhenRequired lock1(...);
  Bar();
}

void Bar() {
  ScopedLockWhenRequired lock2(...);
}

The value of lock2.acquired_thread_id_ is unrelated to that of lock1.acquired_thread_id_. Presumably &lock1.acquired_thread_id_ == &lock2.acquired_thread_id_ so you can catch attempts to relock the mutex from the same thread.

**Comment by xiaomings** [comment]
You're right, I will have a follow up CL to pass in |acquired_thread_id_|.  Thank you.

**Pull request merged**
