### PR TITLE
[XB1] Player switches to avc1 codec after suspend/resume

### PR DESCRIPTION
**Pull request by victorpasoshnikov**
b/173550025

Change-Id: I72d733e1036c672de491b627c0026ddf88345426

### CODE REVIEW

**Comment by victorpasoshnikov** [comment]
> 4\. the cache of supported codecs

**Comment by victorpasoshnikov** [comment]
> When you say don't clear the cache

I mean removing this code
    if (is_av1_shader_compiled_ && is_vp9_shader_compiled_) {
      MimeSupportabilityCache::GetInstance()->ClearCachedMimeSupportabilities();
    }
MimeSupportabilities is std::vector in memory. It consists of few elements and needs in small amount of memory

**Comment by victorpasoshnikov** [comment]
> 5\. don't release compiled shaders

I mean don't call
        Av1VideoDecoder::ReleaseShaders();
        VpxVideoDecoder::ReleaseShaders();
In this case decoders will keep their compiled shaders, i.e. binary arrays in memory. There are not too large to take them into account

**Comment by victorpasoshnikov** [comment]
And keep in mind that this PR depends on #1524. If you make positive decision for current PR, please don't merge it before I do rebase & may be refactoring of it.

**Comment by TyHolc** [comment]
> > 5. don't release compiled shaders
> 
> I mean don't call Av1VideoDecoder::ReleaseShaders(); VpxVideoDecoder::ReleaseShaders(); In this case decoders will keep their compiled shaders, i.e. binary arrays in memory. There are not too large to take them into account

I don't think we should keep memory while in a suspended state, I tried to find documentation from Microsoft to see if there was precedent for that but I couldn't.

Is the codec switching very noticeable to users? If not, I think we can leave it as-is.

**Comment by amurovanyi** [comment]
> Is the codec switching very noticeable to users?

By switching to AVC in the worst case users loose 2K resolution and HDR. For high quality videos this may be quite noticeable.

**Comment by TyHolc** [comment]
> > > 5. don't release compiled shaders
> > 
> > 
> > I mean don't call Av1VideoDecoder::ReleaseShaders(); VpxVideoDecoder::ReleaseShaders(); In this case decoders will keep their compiled shaders, i.e. binary arrays in memory. There are not too large to take them into account
> 
> I don't think we should keep memory while in a suspended state, I tried to find documentation from Microsoft to see if there was precedent for that but I couldn't.
> 
> Is the codec switching very noticeable to users? If not, I think we can leave it as-is.

I'm still not fully convinced we should keep shaders in-memory in a suspended state. @jasonzhangxx can you take a look?

**Review by jasonzhangxx — APPROVED** [review]

**Pull request merged**
