### PR TITLE
Enable Android test coverage report.

### PR DESCRIPTION
**Pull request by zhongqiliang**
b/213241647

Screenshot 2023-05-17 at 12 30 44

Instruction to create the report.
1. cd ./starboard/android/apk
2. ./gradlew createDebugCoverageReport
3. the report is under ./cobalt/out/android_studio/gradle/build/app/reports/coverage/androidTest/debug/index.html

### CODE REVIEW

**Comment by kaidokert** [comment]
This looks okay to me overall, just one question - besides putting out an `index.html` file, is Gradle able to generate the JUnit format XML file output from this run as well ? It would be really helpful if it did, because we can plug this into continus test tracking dashboards.

**Comment by zhongqiliang** [comment]
It does, the xml file path is
./cobalt/out/android_studio/gradle/build/app/reports/coverage/androidTest/debug/report.xml

**Review by kaidokert — APPROVED** [review]
lgtm to go in

**Comment by zhongqiliang** [comment]
Android Gradle plugin has problem with the coverage report. b/276709044

**Pull request merged**
