### PR TITLE
Update Bug ID check logic

### PR DESCRIPTION
**Pull request by isarkis**
Check PR description for bug id which gets derived from the first commit message.

b/283308580

### CODE REVIEW

**Comment by andrewsavage1** [comment]
We had it this way originally and it also confused people. Also, this would make i.e. the rebase and merge strategy more annoying to enable, as we could have commits that don't have bug numbers in that case

**Comment by joeltine** [comment]
My 2c: this change LGTM and I still think it fits with other people's workflows as the first commit becomes the PR description automatically.

**Review by joeltine — APPROVED** [review]

**Review by kaidokert — CHANGES_REQUESTED** [review]
Lets hold this for a bit, as it's not super urgent - we may have a more structured approach to this, but it needs more discussion

**Review by andrewsavage1 — APPROVED** [review]
Let's see if we can merge this in and send an announcement to the team

**Comment by andrewsavage1** [comment]
Tested in https://github.com/youtube/cobalt_sandbox/pull/493, https://github.com/youtube/cobalt_sandbox/pull/494, and https://github.com/youtube/cobalt_sandbox/pull/495. See b/283308580 for updates

**Review by kaidokert — APPROVED** [review]
LGTM with Andrews tests

**Pull request merged**
