### PR TITLE
Make linux-x64x11 the default platform in gn.py

### PR DESCRIPTION
**Pull request by dahlstrom-g**
b/190628619

### CODE REVIEW

**Comment by joeltine** [comment]
Does this mean the most basic gn.py command is now this?

```
python ./cobalt/build/gn.py -c devel
```

**Review by joeltine — APPROVED** [review]

**Comment by dahlstrom-g** [comment]
You can already omit `-c devel`:
https://github.com/youtube/cobalt/blob/4f209bbf/cobalt/build/gn.py#L78

**Comment by kaidokert** [comment]
> You can already omit `-c devel`: https://github.com/youtube/cobalt/blob/4f209bbf/cobalt/build/gn.py#L78

Also no need to type out python, it's just `cobalt/build/gn.py` - and i'm not sure why we kept the `.py` extension, we can make a shorter alias that is just `cobalt/build/gn`

**Comment by andrewsavage1** [comment]
> Also no need to type out python, it's just `cobalt/build/gn.py` - and i'm not sure why we kept the `.py` extension, we can make a shorter alias that is just `cobalt/build/gn`

I don't want to give it the same name as the executable and have people/systems use this when they mean to use the actual tool and vice versa. the two act pretty differently

**Comment by kaidokert** [comment]
> I don't want to give it the same name as the executable and have people/systems use this when they mean to use the actual tool and vice versa. the two act pretty differently

Yep, that makes perfect sense.

**Pull request merged**
