### PR TITLE
Auto-label PRs by outside collaborators

### PR DESCRIPTION
**Pull request by andrewsavage1**
b/261052420

### CODE REVIEW

**Comment by andrewsavage1** [comment]
@lamdbui it would be good to hear what we want this to look like—whether it should be auto-assignment, a label automatically applied to the PR, or something else entirely

**Comment by andrewsavage1** [comment]
See an example here: https://github.com/youtube/cobalt_sandbox/pull/467

**Comment by kaidokert** [comment]
> @lamdbui it would be good to hear what we want this to look like—whether it should be auto-assignment, a label automatically applied to the PR, or something else entirely

I'd start with a label, as it is now. Easy to make a go-link that just shows pending ones.

**Comment by kaidokert** [comment]
Quick ping on this - seems like a good thing to land. @lamdbui

**Review by lamdbui — APPROVED** [review]

**Pull request merged**
