### PR TITLE
Update BoringSSL from Chromium 114.0.5735.355

### PR DESCRIPTION
**Pull request by dahlstrom-g**
b/309016038

### CODE REVIEW

**Comment by andrewsavage1** [comment]
It's annoying, but for https://github.com/youtube/cobalt/actions/runs/8378033616/job/22942288588?pr=2666#step:7:166 you'll want to remove `__ctype_b_loc` from the list of leaked files in the stub/gold manifests (see https://github.com/search?q=repo%3Ayoutube%2Fcobalt+__ctype_b_loc+path%3A**%2Fstub%2Fgold%2F**&type=code)

**Comment by dahlstrom-g** [comment]
> It's annoying, but for https://github.com/youtube/cobalt/actions/runs/8378033616/job/22942288588?pr=2666#step:7:166 you'll want to remove `__ctype_b_loc` from the list of leaked files in the stub/gold manifests (see https://github.com/search?q=repo%3Ayoutube%2Fcobalt+__ctype_b_loc+path%3A**%2Fstub%2Fgold%2F**&type=code)

done

**Comment by andrewsavage1** [comment]
> > It's annoying, but for [youtube/cobalt/actions/runs/8378033616/job/22942288588?pr=2666#step:7:166](https://github.com/youtube/cobalt/actions/runs/8378033616/job/22942288588?pr=2666#step:7:166) you'll want to remove `__ctype_b_loc` from the list of leaked files in the stub/gold manifests (see [github.com/search?q=repo%3Ayoutube%2Fcobalt+__ctype_b_loc+path%3A**%2Fstub%2Fgold%2F**&type=code](https://github.com/search?q=repo%3Ayoutube%2Fcobalt+__ctype_b_loc+path%3A**%2Fstub%2Fgold%2F**&type=code))
> 
> done

I'm pretty sure we'd want to remove the symbol from all 3 manifests in the search result as the different manifests are used in different contexts.

**Comment by dahlstrom-g** [comment]
> I'm pretty sure we'd want to remove the symbol from all 3 manifests in the search result as the different manifests are used in different contexts.

Done but I'd like to know about those contexts
and be more than pretty sure if possible.
I'm somewhat uncomfortable making changes
I don't understand and can't verify.

**Comment by andrewsavage1** [comment]
> > I'm pretty sure we'd want to remove the symbol from all 3 manifests in the search result as the different manifests are used in different contexts.
> 
> Done but I'd like to know about those contexts and be more than pretty sure if possible. I'm somewhat uncomfortable making changes I don't understand and can't verify.

`manifest` is used locally and debian10 is used for docker images with a debian10 base image

**Comment by dahlstrom-g** [comment]
> `manifest` is used locally and debian10 is used for docker images with a debian10 base image

Do you know when and how it's used locally?
When I ran `api_leak_detector.py` I used `gn_built_docker_debian11_manifest`
because that was the failure I was trying to fix.

That aside, is this ready to submit?

**Review by andrewsavage1 — APPROVED** [review]
Sorry for the wait, this lgtm

`manifest` is used by default for glinux, and the versioned debian  manifests correspond to their respective image

**Pull request merged**
