### PR TITLE
Merge Skia commit from branch chrome/m79

### PR DESCRIPTION
**Pull request by dahlstrom-g**
This follows up after commit dd32e43e (rewritten as commit 338060fe)
to provide an appropriate “latest squash” for the `git-subtree.sh` contrib script.
No files are changed relative to Cobalt's `main` branch.

### CODE REVIEW

**Comment by kaidokert** [comment]
Huh, the CLA check failure here is unexpected, it points at the original commit author. We haven't run into this before.  Ideally i wouldn't want to change the commit and author info to get the CLA check to pass, but we also can't go around it.

I'd expect this is going to happen again so i think we should figure out how to do this right.

**Comment by dahlstrom-g** [comment]
> Huh, the CLA check failure here is unexpected, it points at the original commit author. We haven't run into this before. Ideally i wouldn't want to change the commit and author info to get the CLA check to pass, but we also can't go around it.
> 
> I'd expect this is going to happen again so i think we should figure out how to do this right.

Here, with a commit that's both third-party and squashed, the check is irrelevant in multiple ways.
Also I'm somewhat surprised it failed when the commit author belongs to the Google org.

**Review by kaidokert — APPROVED** [review]
this lgtm, as it doesn't change the files.

**Comment by kaidokert** [comment]
Do you want to go ahead and get this merged in trunk ? Currently this need admin powers, i can get it submitted if it's otherwise ready.

**Comment by dahlstrom-g** [comment]
> Do you want to go ahead and get this merged in trunk ? Currently this need admin powers, i can get it submitted if it's otherwise ready.

Yep, let's do it.

**Pull request merged**
