### PR TITLE
Not use unique_ptr to store debugger values

### PR DESCRIPTION
**Pull request by johnxwork**
Debugger was leaking memory because base::Value stopped supporting storing std::unique_ptr as its value but we tried to keep real values in base::Value. This CL abandons all usage of unique_ptr in debugger code and stores real variable values everywhere.

b/333556585

Change-Id: Ifb2b21163a267247dbe5f85bac69a56014064d74

### CODE REVIEW

**Comment by sherryzy** [comment]
Looking good. Can you take a look if those win32 builds failures are related?

**Comment by johnxwork** [comment]
> Looking good. Can you take a look if those win32 builds failures are related?

Both of the windows builder failures were due to "There is not enough space on the disk" so likely worker disk issues.

**Comment by andrewsavage1** [comment]
> > Looking good. Can you take a look if those win32 builds failures are related?
> 
> Both of the windows builder failures were due to "There is not enough space on the disk" so likely worker disk issues.

I'll retry the win builds

**Comment by johnxwork** [comment]
The linux failure was due to nplb failing which shouldn't be possible to be caused by the cobalt directory changes here. And the Android failures happened during apk packaging which looks also to be builder issues.

**Review by andrewsavage1 — APPROVED** [review]

**Pull request merged**
