### PR TITLE
Run on device tests on nightly workflows

### PR DESCRIPTION
**Pull request by andrewsavage1**
b/280308547

### CODE REVIEW

**Comment by andrewsavage1** [comment]
Hard to test this until the nightly trigger happens—could try running `act` locally though

**Comment by kaidokert** [comment]
I guess this also tells me the change's weren't cherry-picked yet to older branches, because those kept running.

**Review by kaidokert — APPROVED** [review]
To test, we may want to tweak the "nightly" schedule on Sandbox to trigger every 15 minutes.

**Review by isarkis — APPROVED** [review]

**Comment by andrewsavage1** [comment]
Tested, works in https://github.com/youtube/cobalt_sandbox/actions/runs/4864679467

**Pull request merged**
