### PR TITLE
Initial pass of removing scoped_ptr/scoped_array

### PR DESCRIPTION
**Pull request by kaidokert**
Switches to use unique_ptr instead of scoped_ptr where possible and it doesn't break tests.

The intent is to remove starboard/common/scoped_ptr fully.

b/291356560

### CODE REVIEW

**Review by jellefoks — APPROVED** [review]

**Review by joeltine — CHANGES_REQUESTED** [review]
LGTM but can you tell me if the current test failures are legitimate?

**Comment by kaidokert** [comment]
> LGTM but can you tell me if the current test failures are legitimate?

For internal builds they are yes. Haven't had time to debug - i've been backing changes out one by one. External builds are ( were ? ) fine, except that the lab has been down for couple days for on-device tests.

**Comment by joeltine** [comment]
> For internal builds they are yes. Haven't had time to debug - i've been backing changes out one by one. External builds are ( were ? ) fine, except that the lab has been down for couple days for on-device tests.

OK LMK when tests are passing.

**Comment by kaidokert** [comment]
This is now worked on in https://github.com/youtube/cobalt/pull/2427

Conveerting to a draft

**Pull request closed without merging**
