### PR TITLE
Avoid using gtest functions in SbPlayerTestFixture

### PR DESCRIPTION
**Pull request by jasonzhangxx**
The gtest lib we're using doesn't support multi-threads. It's not safe to call any gtest functions out of main thread. To better support multi player tests, which requires SbPlayerTestFixture to be available from multiple threads, we need to remove all gtest functions from SbPlayerTestFixture implementation.

b/274493767

### CODE REVIEW

**Comment by kaidokert** [comment]
> The gtest lib we're using doesn't support multi-threads. 

Can we address this by updating to latest GTest, rather ? I would prefer to avoid custom testing macros, if it's solved by updating to newer standard GTest code from upstream ?

**Comment by sideb0ard** [comment]
> 

Yeah, was going to say something similar!
We're trying to make a big push to do more testing, so definitely don't want to remove gtest functions. Updating Gtest would be a hero move! Especially with FixIt week coming up next week, we could take the time to work on updating?

**Comment by xiaomings** [comment]
Jason discussed with me before implementing the CL on whether we should update GoogleTest instead, and my concern against updating is the amount of effort involved and its effect the C24 timeline.  Let's discuss offline for this.

**Comment by sideb0ard** [comment]
> Jason discussed with me before implementing the CL on whether we should update GoogleTest instead, and my concern against updating is the amount of effort involved and its effect the C24 timeline. Let's discuss offline for this.

Definitely not the direction we want to move in! :(
I don't see any bug filed for the gtest limitation - is there one? If its a blocker, you have to let people know. As I mentioned in the talk yesterday, Testing is not a QA or Tools and Infra problem, it's on all of us. If Gtest needs updated, someone has to do it, and if we need the functionality, then it should be us.

**Comment by xiaomings** [comment]
Created b/280671902 to track the effort of the rebasing.

**Pull request closed without merging**
