### PR TITLE
Use native_target/crashpad_handler in builds+tests

### PR DESCRIPTION
**Pull request by hlwarriner**
b/270858365

Change-Id: Iadc88b422360335096e23e436d7b02225e017291

### CODE REVIEW

**Comment by hlwarriner** [comment]
The `android-arm64 / arm64_on_device_2` failure looks like an infra issue: the tests all show as passing at https://fusion2.corp.google.com/invocations/4fea0782-7ca2-453d-b7f5-16939f57682d/targets/%2F%2Fvideo%2Fyoutube%2Ftesting%2Fmaneki%2Fcobalt%2Funit_tests:cobalt_android_arm64_unit_tests/tests.

**Comment by oxve** [comment]
The green on sponge and red here is a bug in our infra, it does not mean that all tests passed unfortunately. If you check the log you'll find that nplb crashed while running some media tests. Looks to me like it could be a device issue and probably not related to your change.

Can you take a look to make sure it isn't?

**Comment by hlwarriner** [comment]
> The green on sponge and red here is a bug in our infra, it does not mean that all tests passed unfortunately. If you check the log you'll find that nplb crashed while running some media tests. Looks to me like it could be a device issue and probably not related to your change.
> 
> Can you take a look to make sure it isn't?

Interesting, thanks. Sounds good - I may retry the test once or twice but if it continues to fail will look at the logs to confirm it's not related.

**Comment by hlwarriner** [comment]
> > The green on sponge and red here is a bug in our infra, it does not mean that all tests passed unfortunately. If you check the log you'll find that nplb crashed while running some media tests. Looks to me like it could be a device issue and probably not related to your change.
> > Can you take a look to make sure it isn't?
> 
> Interesting, thanks. Sounds good - I may retry the test once or twice but if it continues to fail will look at the logs to confirm it's not related.

The retry succeeded.

**Review by oxve — APPROVED** [review]

**Review by y4vor — APPROVED** [review]

**Pull request merged**
