### PR TITLE
Revert "Update components/update_client to 78.0.3904.106"

### PR DESCRIPTION
**Pull request by andrewsavage1**
Reverts youtube/cobalt#1579

The update broke evergreen tests.

b/139069508

### CODE REVIEW

**Comment by andrewsavage1** [comment]
@dahlstrom-g is there a better bug number than the one used in the original PR, b/139069508? That one is not all that relevant to this update.

**Review by dahlstrom-g — APPROVED** [review]
Odd; I ran a try build and reviewed the results.
I'm curious what I missed.

**Comment by andrewsavage1** [comment]
> #1579

See https://github.com/youtube/cobalt/actions/runs/6243439850/job/16949115493?pr=1579

**Comment by dahlstrom-g** [comment]
> b/139069508

That's the most relevant one I found.
I guess there could be a generic issue for fixing imported code.

**Comment by dahlstrom-g** [comment]
> We probably need an issue for incorporating [commit afaa2923](http://chromium.googlesource.com/chromium/src/+/afaa2923). I suspect the problem here may be associated with that.

Reverting is the right impulse but I suspect
we need to fix our tests one way or another.
I've tentatively reported b/301290376.

On reflection I'm not sure reverting all of #1579
is the best thing to do here. Possibly we should
revert just commit afaa2923. Moreover since
this is in a transplanted tree, flatly reversing
the diff doesn't remove the squash commit,
which makes this PR and its effect on history
somewhat misleading.

**Comment by andrewsavage1** [comment]
> On reflection I'm not sure reverting all of #1579 is the best thing to do here. Possibly we should revert just commit afaa2923. Moreover since this is in a transplanted tree, flatly reversing the diff doesn't remove the squash commit, which makes this PR and its effect on history somewhat misleading.

Feel free to follow up with a new PR with whatever history, but I am going to hard revert any changes that break required checks unless there's actively a PR to fix it

**Pull request merged**
