### PR TITLE
Fix PixelTests.

### PR DESCRIPTION
**Pull request by jellefoks**
Fixes for PixelTests.

Adjust for UTF16CharIterator API change to fix PixelTests, and clear default families from previous locale and minor cleanup.

b/329899074

### CODE REVIEW

**Comment by jellefoks** [comment]
Hmm. I can reproduce these on `linux-modular` when I run the entire test. When I run only the failing tests, they pass...

```
[  FAILED  ] 2 tests, listed below:
[  FAILED  ] PixelTest.SimpleTextInRed40PtThaiFont
[  FAILED  ] PixelTest.SimpleTextInRed40PtChineseFont
```

**Comment by jellefoks** [comment]
> Hmm. I can reproduce these on `linux-modular` when I run the entire test. When I run only the failing tests, they pass...
> 
> ```
> [  FAILED  ] 2 tests, listed below:
> [  FAILED  ] PixelTest.SimpleTextInRed40PtThaiFont
> [  FAILED  ] PixelTest.SimpleTextInRed40PtChineseFont
> ```

It seems to be a font selection issue. When run by themselves, they use `NotoSansThaiUI-Regular.woff2` and `NotoSansCJK-Regular.woff2` resp, but when preceded by `AnimationsTest.*`, a different font file `NotoSansCJK-Regular.woff2` is chosen for the test.

**Comment by jellefoks** [comment]
> > Hmm. I can reproduce these on `linux-modular` when I run the entire test. When I run only the failing tests, they pass...
> > ```
> > [  FAILED  ] 2 tests, listed below:
> > [  FAILED  ] PixelTest.SimpleTextInRed40PtThaiFont
> > [  FAILED  ] PixelTest.SimpleTextInRed40PtChineseFont
> > ```
> 
> It seems to be a font selection issue. When run by themselves, they use `NotoSansThaiUI-Regular.woff2` and `NotoSansCJK-Regular.woff2` resp, but when preceded by `AnimationsTest.*`, a different font file `NotoSansCJK-Regular.woff2` is chosen for the test. The isssue does not occur on trunk, or strangely on the non-modular build.

`uloc_addLikelySubtags` doesn't seem to work in the modular build, which caused more default fonts to be loaded by `LoadLocaleDefault`, and due to `LoadLocaleDefault` not clearing the previous list of default fonts, that spilled over into these two tests causing it to render with a different font.

**Comment by jellefoks** [comment]
> > > Hmm. I can reproduce these on `linux-modular` when I run the entire test. When I run only the failing tests, they pass...
> > > ```
> > > [  FAILED  ] 2 tests, listed below:
> > > [  FAILED  ] PixelTest.SimpleTextInRed40PtThaiFont
> > > [  FAILED  ] PixelTest.SimpleTextInRed40PtChineseFont
> > > ```
> > 
> > 
> > It seems to be a font selection issue. When run by themselves, they use `NotoSansThaiUI-Regular.woff2` and `NotoSansCJK-Regular.woff2` resp, but when preceded by `AnimationsTest.*`, a different font file `NotoSansCJK-Regular.woff2` is chosen for the test. The isssue does not occur on trunk, or strangely on the non-modular build.
> 
> `uloc_addLikelySubtags` doesn't seem to work in the modular build, which caused more default fonts to be loaded by `LoadLocaleDefault`, and due to `LoadLocaleDefault` not clearing the previous list of default fonts, that spilled over into these two tests causing it to render with a different font.

There are a few things different in modular vs non-modular that highlight some existing bugs: In modular, more fonts are loaded as `default_families_` into the font manager during the `AnimationsTest`, as a result of the ICU returning a different value for the call to `base::GetSystemLanguageScript()`, and as a result when these `PixelTest are run afterwards a different font is selected for rendering during those tests. The fonts loaded in the font manager are not cleared between tests, even though the `renderer::Pipeline`is recreated, because when the `ResourceProvider` calls `LoadLocaleDefault` on the font manager, any lingering fonts from a previous locale initialization weren't cleared.

The reason why ICU returns a different value for the system languague script has to do with the initialization of the `ures` cache. For all builds, the cache is initialized before the unit tests suite starts, but for the modular build that cache is empty by the time the test starts while for non-modular builds the cache is retained, resulting in the different output for the system languague script. 

The root cause for that is still under investigation, but may not need to be solved to pass these tests, given that the font manager `default_families_` fix will address the symptom that caused these tests to fail. If that proves correct, fixing the ICU initialization issue will be done as a followup task.

**Review by sherryzy — APPROVED** [review]

**Pull request merged**
