### PR TITLE
Create copy of android directories for aosp

### PR DESCRIPTION
**Pull request by andrewsavage1**
b/379129385

### CODE REVIEW

**Comment by andrewsavage1** [comment]
My worry with this is that it will cause some confusion, i.e. people may find a file under aosp/ that they believe is included in the build when it isn't. Can someone re-explain to me why this is better than bringing over a copy of the android/ code from a certain point in git history once it's needed?

**Comment by y4vor** [comment]
> My worry with this is that it will cause some confusion, i.e. people may find a file under aosp/ that they believe is included in the build when it isn't. Can someone re-explain to me why this is better than bringing over a copy of the android/ code from a certain point in git history once it's needed?

My suggestion was to just preserve the existing code with  SB_IS(EVERGREEN_COMPATIBLE). This way we can share most of the code, but still have separate paths. Also I was thinking we might use it sooner, but based on the current infra issues, that seem unlikely.

**Comment by andrewsavage1** [comment]
> My suggestion was to just preserve the existing code with SB_IS(EVERGREEN_COMPATIBLE). This way we can share most of the code, but still have separate paths. Also I was thinking we might use it sooner, but based on the current infra issues, that seem unlikely.

The code is always preserved in git history, is that sufficient? If at some point we need it in trunk again, we can just pull it from history as it was

**Comment by andrewsavage1** [comment]
> Sure, I think this is fine given that we can't get AOSP builds on the build infra short term.

Great, sounds good, closing!

**Pull request closed without merging**
